### ISSUE TITLE
speculator with adaptive mcmc

### ISSUE THREAD

**Issue by changhoonhahn** [changhoonhahn/gqp_mc#24]
@kgb0255 implemented adaptive MCMC. We need to re-run LGal SED fits with speculator with this new feature.

**Comment by changhoonhahn** [comment]
In commit 5703716bec58972a9642f78808c5f67c5cc6affd , I've updated `gqp_mc.fitters.py` so that ARM is now optional. It only runs when you set kwarg `niter='adaptive'` and runs normal mcmc when you specify an integer. 

@kgb0255 I've tested the updates locally but you should test that they all work on NERSC.

**Comment by kgb0255** [comment]
@changhoonhahn Thank you for the update. I'll go ahead and test run some chains on NERSC.

**Comment by kgb0255** [comment]
I received following error when I ran the chain on the interactive mode.
> Traceback (most recent call last):
  File "/global/homes/k/kgb0255/packages/gqp_mc/run/mini_mocha.py", line 743, in <module>
    justplot=justplot)
  File "/global/homes/k/kgb0255/packages/gqp_mc/run/mini_mocha.py", line 509, in MP_sed_fit
    for igal in args: fit_func(igal, **kwargs)
  File "/global/homes/k/kgb0255/packages/gqp_mc/run/mini_mocha.py", line 312, in fit_spectrophotometry
    specs, meta = Data.Spectra(sim=sim, noise=noise_spec, lib='bc03', sample='mini_mocha')
  File "/global/homes/k/kgb0255/.local/lib/python3.7/site-packages/gqp_mc-0.1-py3.7.egg/gqp_mc/data.py", line 54, in Spectra
    meta, mock = read_data(sim=sim, noise=noise, lib=lib, sample=sample)
  File "/global/homes/k/kgb0255/.local/lib/python3.7/site-packages/gqp_mc-0.1-py3.7.egg/gqp_mc/data.py", line 153, in read_data
    'lgal.%s.hdf5' % dat_descrip), 'r')
  File "/global/homes/k/kgb0255/.conda/envs/gqp/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/global/homes/k/kgb0255/.conda/envs/gqp/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 524, error message = 'Unknown error 524')

This error was resolved when I added this in ~/.bashrc.ext 

> export HDF5_USE_FILE_LOCKING='FALSE'

**Comment by changhoonhahn** [comment]
@msiudek The above solution by @kgb0255 is also what I did to solve the issue.

**Comment by kgb0255** [comment]
Chain was ran for igal = 2. Some walkers did not move at all. I sent the report to @changhoonhahn email address and it can also be found [here].(https://github.com/kgb0255/GQPMC_v2_JAMES/blob/94c56618895d468796a61cbac2de14569bdd65ea/Reports/GQPMC%20Report7.pdf) Plots are included in the report.
